version: '3'

services:
  scraper:
    build: .
    depends_on:
      - database
      - selenium-server
    environment:
      SELENIUM_HOST: selenium-server
    tty: true
    stdin_open: true
    env_file: .env
    volumes:
      - .:/app
      - bundler-store:/usr/local/bundle
    ports:
      - 3000:3000

  database:
    image: postgres
    environment:
     POSTGRES_USER: job-scrapper-app
     POSTGRES_PASSWORD: job-scrapper-app
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  selenium-server:
    image: selenium/standalone-chrome-debug
    ports:
      - 4444:4444
      - 5900:5900
    volumes:
      - /dev/shm:/dev/shm

volumes:
  db_data:
  bundler-store:
